// Generated by tools/build-icons.py -- do not edit.
'use strict';

const ICONS = {
  "check_box": "\ue834",
  "check_box_outline_blank": "\ue835",
  "close": "\ue14c",
  "edit_note": "\ue745",
  "hourglass_bottom": "\uea5c",
  "local_cafe": "\ue541",
  "music_note": "\ue3a1",
  "pause": "\ue034",
  "play_arrow": "\ue037",
  "replay": "\ue042",
  "resume": "\uf7d0",
  "skip_next": "\ue044",
  "timer_off": "\ue426",
};

/** Set an element's glyph by icon name. Unknown names draw nothing. */
function setIcon(el, name) {
  if (el) el.textContent = ICONS[name] || '';
}

/** Fill in every <span class="icon" data-icon="..."> under root. */
function applyIcons(root) {
  for (const el of (root || document).querySelectorAll('[data-icon]')) {
    setIcon(el, el.dataset.icon);
  }
}

if (typeof module !== 'undefined') module.exports = { ICONS };
