#!/usr/bin/env python3
"""Build the bundled icon font.

The app must not depend on a font being installed on the machine: Material
Symbols ships with caelestia on Linux but is absent on a stock Windows box,
where the ligature names ("play_arrow") render as literal words and wreck the
layout. So we ship a subset, and address glyphs by codepoint rather than by
ligature, which also means a missing font degrades to one blank box instead of
a paragraph.

  python3 tools/build-icons.py [path-to-MaterialSymbolsRounded-variable.ttf]

Writes assets/fonts/icons.ttf and src/renderer/icons.js.
"""
import json
import pathlib
import sys

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

# Every icon the UI can show. Keep in sync with the renderers; test/icons.test.js
# fails the build if a renderer names one that is not here.
ICONS = [
    "check_box",
    "check_box_outline_blank",
    "close",
    "edit_note",
    "hourglass_bottom",
    "local_cafe",
    "music_note",
    "pause",
    "play_arrow",
    "replay",
    "resume",
    "skip_next",
    "timer_off",
]

DEFAULT_SRC = "/usr/share/fonts/TTF/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf"
HERE = pathlib.Path(__file__).resolve().parent.parent


def main(argv):
    src = argv[1] if len(argv) > 1 else DEFAULT_SRC
    font = TTFont(src)

    # Glyph name -> codepoint, so we can address icons without ligatures.
    cmap = font.getBestCmap()
    by_glyph = {}
    for cp, glyph in cmap.items():
        by_glyph.setdefault(glyph, cp)

    missing = [n for n in ICONS if n not in by_glyph]
    if missing:
        print(f"not in this font: {', '.join(missing)}", file=sys.stderr)
        return 1

    codepoints = {n: by_glyph[n] for n in ICONS}

    # Pin the variable axes to the weight the UI uses, so the shipped file is a
    # plain static font with no variation tables.
    font = instancer.instantiateVariableFont(
        font, {"FILL": 0, "GRAD": 0, "opsz": 24, "wght": 400}, inplace=True
    )

    subsetter = subset.Subsetter(
        options=subset.Options(
            layout_features=[],      # no ligatures needed; we use codepoints
            name_IDs=[1, 2, 3, 4, 6],
            notdef_outline=True,
            recalc_bounds=True,
        )
    )
    subsetter.populate(unicodes=list(codepoints.values()))
    subsetter.subset(font)

    out_font = HERE / "assets" / "fonts" / "icons.ttf"
    out_font.parent.mkdir(parents=True, exist_ok=True)
    font.save(out_font)

    # Emitted as a script rather than JSON so the renderers can load it with a
    # plain <script> tag, and the test can require() it.
    entries = "\n".join(
        f'  {json.dumps(n)}: "\\u{cp:04x}",' for n, cp in sorted(codepoints.items())
    )
    out_map = HERE / "src" / "renderer" / "icons.js"
    out_map.write_text(
        "// Generated by tools/build-icons.py -- do not edit.\n"
        "'use strict';\n\n"
        "const ICONS = {\n" + entries + "\n};\n\n"
        "/** Set an element's glyph by icon name. Unknown names draw nothing. */\n"
        "function setIcon(el, name) {\n"
        "  if (el) el.textContent = ICONS[name] || '';\n"
        "}\n\n"
        "/** Fill in every <span class=\"icon\" data-icon=\"...\"> under root. */\n"
        "function applyIcons(root) {\n"
        "  for (const el of (root || document).querySelectorAll('[data-icon]')) {\n"
        "    setIcon(el, el.dataset.icon);\n"
        "  }\n"
        "}\n\n"
        "if (typeof module !== 'undefined') module.exports = { ICONS };\n"
    )

    kb = out_font.stat().st_size / 1024
    print(f"{len(ICONS)} icons -> {out_font.relative_to(HERE)} ({kb:.1f} KB)")
    for n, cp in sorted(codepoints.items()):
        print(f"  {n:<24} U+{cp:04X}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
